apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-local-dns
  namespace: pihole
data:
  05-local-dns.conf: |
    {{- range .Values.ingressHosts }}
    address=/{{ . }}/{{ $.Values.ingressAddress }}
    {{- end }}
    {{- range $host, $ip := .Values.localHosts }}
    address=/{{ $host }}/{{ $ip }}
    {{- end }}
    filter-AAAA
    filter-rr=HTTPS
    filter-rr=SVCB
